# Model arguments
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# PEFT arguments
load_in_4bit: true
use_peft: true
lora_r: 16
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
- gate_proj
- up_proj
- down_proj

# Data training arguments
dataset_num_proc: 48

# SFT trainer config
bf16: true
do_eval: false
eval_strategy: 'no'
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 1.0e-4
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.1
packing: false
max_seq_length: 16384
max_steps: -1
num_train_epochs: 1
overwrite_output_dir: true
per_device_train_batch_size: 1
push_to_hub: false
report_to:
- wandb
save_strategy: "epoch"
save_total_limit: 1
seed: 42
use_liger: true
warmup_ratio: 0.05
ddp_timeout: 7200